# Generated by Django 6.0.1 on 2026-01-27 10:02

import apps.products.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="shopkeeper",
            field=models.ForeignKey(
                blank=True,
                help_text="Shopkeeper who owns this product",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                help_text="Product brand (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.brand",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                help_text="Product category",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="products.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="compare_at_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Original price (for showing discounts)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cost price (for profit calculation)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(help_text="Full product description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Featured product (shown on homepage)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_description",
            field=models.TextField(blank=True, help_text="SEO meta description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="meta_title",
            field=models.CharField(
                blank=True, help_text="SEO title tag", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(help_text="Product name", max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Current selling price",
                max_digits=10,
                validators=[apps.products.validators.validate_price],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.CharField(
                blank=True, help_text="Brief description for listings", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                help_text="Stock Keeping Unit",
                max_length=100,
                unique=True,
                validators=[apps.products.validators.validate_sku],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                help_text="URL-friendly product identifier", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PUBLISHED", "Published"),
                    ("OUT_OF_STOCK", "Out of Stock"),
                    ("DISCONTINUED", "Discontinued"),
                ],
                db_index=True,
                default="DRAFT",
                help_text="Product status",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["shopkeeper", "status"], name="products_pr_shopkee_22a2bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "status"], name="products_pr_categor_75eeb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_featured", "status"], name="products_pr_is_feat_bd97b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="products_pr_price_9b1a5f_idx"),
        ),
    ]
