# Generated by Django 6.0 on 2026-02-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_emailchangetoken_passwordresettoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passwordresettoken",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="passwordresettoken",
            name="user_agent",
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("FAILED_LOGIN", "Failed Login"),
                    ("PASSWORD_CHANGE", "Password Change"),
                    ("PASSWORD_RESET_REQUEST", "Password Reset Request"),
                    ("PASSWORD_RESET_COMPLETE", "Password Reset Complete"),
                    ("EMAIL_VERIFICATION", "Email Verification"),
                    ("EMAIL_CHANGE_REQUEST", "Email Change Request"),
                    ("EMAIL_CHANGE_COMPLETE", "Email Change Complete"),
                    ("PHONE_CHANGE", "Phone Number Change"),
                    ("PROFILE_UPDATE", "Profile Update"),
                    ("ACCOUNT_CREATED", "Account Created"),
                    ("ACCOUNT_DEACTIVATED", "Account Deactivated"),
                    ("ACCOUNT_REACTIVATED", "Account Reactivated"),
                    ("SESSION_REVOKED", "Session Revoked"),
                    ("TWO_FACTOR_ENABLED", "Two-Factor Authentication Enabled"),
                    ("TWO_FACTOR_DISABLED", "Two-Factor Authentication Disabled"),
                ],
                max_length=50,
            ),
        ),
    ]
