# Generated by Django 6.0 on 2026-02-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_passwordresettoken_ip_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopkeeperprofile",
            name="gst_number",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
