# Generated by Django 6.0 on 2026-02-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_shopkeeperprofile_gst_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersession",
            name="session_key",
            field=models.CharField(db_index=True, max_length=512, unique=True),
        ),
    ]
