# Generated by Django 6.0.1 on 2026-01-27 12:29

import apps.reviews.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_options_product_shopkeeper_and_more"),
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Review Like",
                "verbose_name_plural": "Review Likes",
                "db_table": "review_likes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "comment",
                    models.TextField(
                        help_text="Reply comment",
                        max_length=1000,
                        validators=[
                            apps.reviews.validators.validate_reply_comment_length
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Admin can deactivate inappropriate replies",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Reply",
                "verbose_name_plural": "Review Replies",
                "db_table": "review_replies",
                "ordering": ["created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
            },
        ),
        migrations.RemoveField(
            model_name="review",
            name="is_approved",
        ),
        migrations.AddField(
            model_name="review",
            name="helpful_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of users who found this review helpful (liked it)",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Admin can deactivate vulgar or inappropriate reviews",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="is_owner_review",
            field=models.BooleanField(
                default=False, help_text="True if review is from product owner"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(
                help_text="Detailed review comment",
                max_length=2000,
                validators=[apps.reviews.validators.validate_review_comment_length],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="is_verified_purchase",
            field=models.BooleanField(
                default=False, help_text="Whether user actually purchased this product"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                help_text="Product being reviewed",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.DecimalField(
                decimal_places=1,
                help_text="Rating from 1 to 5 (0.5 increments)",
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("1")),
                    django.core.validators.MaxValueValidator(Decimal("5")),
                    apps.reviews.validators.validate_rating,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.CharField(
                help_text="Short review title",
                max_length=100,
                validators=[apps.reviews.validators.validate_review_title_length],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                help_text="User who wrote the review",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["product", "-created_at"], name="reviews_product_500bf4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["product", "-rating"], name="reviews_product_50300a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["product", "-helpful_count"], name="reviews_product_6badee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["is_active", "-created_at"], name="reviews_is_acti_8932e1_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="review",
            table="reviews",
        ),
        migrations.AddField(
            model_name="reviewlike",
            name="review",
            field=models.ForeignKey(
                help_text="Review being liked",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="reviews.review",
            ),
        ),
        migrations.AddField(
            model_name="reviewlike",
            name="user",
            field=models.ForeignKey(
                help_text="User who liked the review",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reviewreply",
            name="review",
            field=models.ForeignKey(
                help_text="Review being replied to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="reviews.review",
            ),
        ),
        migrations.AddField(
            model_name="reviewreply",
            name="user",
            field=models.ForeignKey(
                help_text="User who wrote the reply",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_replies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="reviewlike",
            index=models.Index(
                fields=["review", "-created_at"], name="review_like_review__57ceb1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reviewlike",
            unique_together={("review", "user")},
        ),
        migrations.AddIndex(
            model_name="reviewreply",
            index=models.Index(
                fields=["review", "created_at"], name="review_repl_review__049dc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewreply",
            index=models.Index(
                fields=["is_active", "created_at"],
                name="review_repl_is_acti_1e69f9_idx",
            ),
        ),
    ]
