# Generated by Django 6.0.1 on 2026-01-27 07:39

import apps.addresses.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="address",
            name="phone_number",
        ),
        migrations.AlterField(
            model_name="address",
            name="address_line_1",
            field=models.CharField(
                help_text="Street address, P.O. box, company name", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="address_line_2",
            field=models.CharField(
                blank=True,
                help_text="Apartment, suite, unit, building, floor, etc.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="address_type",
            field=models.CharField(
                choices=[("HOME", "Home"), ("WORK", "Work"), ("OTHER", "Other")],
                default="HOME",
                help_text="Type of address",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(
                help_text="City or district",
                max_length=100,
                validators=[apps.addresses.validators.validate_city],
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(
                default="India",
                help_text="Country name",
                max_length=100,
                validators=[apps.addresses.validators.validate_country],
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="is_default",
            field=models.BooleanField(
                default=False, help_text="Primary address for deliveries"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(help_text="ZIP or postal code", max_length=20),
        ),
        migrations.AlterField(
            model_name="address",
            name="state",
            field=models.CharField(
                help_text="State, province, or region",
                max_length=100,
                validators=[apps.addresses.validators.validate_state],
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                help_text="User who owns this address",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["user", "is_default"], name="addresses_a_user_id_356e69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["user", "address_type"], name="addresses_a_user_id_1792d5_idx"
            ),
        ),
    ]
